name: Biome

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'   # LTS; підійде і 22, якщо хочеш

      - name: Install deps
        run: npm ci

      - name: Biome check
        run: npx biome check .
